export const darkCssVariableOverrides = {
  '--vscode-editor-background': '#24292e',
  '--vscode-editor-foreground': '#e6edf3',
  '--vscode-sideBar-background': '#1f2428',
  '--vscode-panel-border': '#474b50',
  '--vscode-editorWidget-background': '#252a30',
  '--vscode-editorWidget-foreground': '#e6edf3',
  '--vscode-editorHoverWidget-background': '#252a30',
  '--vscode-editorHoverWidget-foreground': '#e6edf3',
  '--vscode-input-background': '#2a3036',
  '--vscode-input-foreground': '#e6edf3',
  '--vscode-input-placeholderForeground': '#8e999e',
  '--vscode-toolbar-hoverBackground': 'rgba(127, 127, 127, 0.18)',
  '--vscode-toolbar-activeBackground': 'rgba(127, 127, 127, 0.32)',
  '--vscode-button-secondaryBackground': '#3a4149',
  '--vscode-button-foreground': '#ffffff',
  '--vscode-descriptionForeground': '#8e999e',
  '--vscode-disabledForeground': '#676f7d',
  '--vscode-icon-foreground': '#c5cbd3',
  '--vscode-textCodeBlock-background': '#1b1f23',
  '--vscode-editor-selectionBackground': '#264f78',
  '--vscode-editorLineNumber-foreground': '#676f7d',
  '--meo-line-number-foreground': '#676f7d',
  '--meo-divider-color': '#474b50',
  '--meo-input-border': '#54595e',
  '--meo-toolbar-overflow-foreground': '#ffffff',
  '--meo-elevated-shadow': '0 4px 12px rgba(0, 0, 0, 0.24)',
  '--meo-fixed-baseline-active-background': 'color-mix(in srgb, var(--vscode-testing-iconPassed, #73c991) 40%, transparent)',
  '--meo-fixed-baseline-active-foreground': '#ffffff',
  '--meo-fixed-baseline-standby': 'var(--vscode-testing-iconPassed, #73c991)',
  '--git-added': '#4a9e82',
  '--git-changed': '#317ae7',
  '--git-deleted': '#e05252'
} as const;
