export const inlineScriptFixtures = [
  { markdown: '~中~', expected: '<sub>中</sub>', subs: ['中'], sups: [], strikes: [] },
  { markdown: '2. 多种~编辑视图和丰富的~配置项；', expected: '多种<sub>编辑视图和丰富的</sub>配置项；', subs: ['编辑视图和丰富的'], sups: [], strikes: [] },
  { markdown: 'H~2~O x^2^ CO~2~', expected: 'H<sub>2</sub>O x<sup>2</sup> CO<sub>2</sub>', subs: ['2', '2'], sups: ['2'], strikes: [] },
  { markdown: '~~删除线~~', expected: '<s>删除线</s>', subs: [], sups: [], strikes: ['删除线'] },
  { markdown: '**~中~** *^上^* ==H~2~O==', expected: '<strong><sub>中</sub></strong> <em><sup>上</sup></em> <mark>H<sub>2</sub>O</mark>', subs: ['中', '2'], sups: ['上'], strikes: [] },
  { markdown: '[H~2~O](https://example.com)', expected: '>H<sub>2</sub>O</a>', subs: ['2'], sups: [], strikes: [] },
  { markdown: '# H~2~O', expected: '>H<sub>2</sub>O</h1>', subs: ['2'], sups: [], strikes: [] },
  { markdown: '| H~2~O |\n| --- |\n| x^2^ |', expected: '<sup>2</sup>', subs: ['2'], sups: ['2'], strikes: [] },
  { markdown: '~two three~ ^two three^', expected: '~two three~ ^two three^', subs: [], sups: [], strikes: [] },
  { markdown: '~two\tthree~ ^two\tthree^', expected: '~two\tthree~ ^two\tthree^', subs: [], sups: [], strikes: [] },
  { markdown: '~two\nthree~ ^two\nthree^', expected: '~two<br />\nthree~ ^two<br />\nthree^', subs: [], sups: [], strikes: [] },
  { markdown: '\\~中\\~ \\^上\\^', expected: '~中~ ^上^', subs: [], sups: [], strikes: [] },
  { markdown: '~two\\ three~ ^two\\ three^', expected: '<sub>two three</sub> <sup>two three</sup>', subs: ['two three'], sups: ['two three'], strikes: [] },
  { markdown: '~a\\~b~ ^a\\^b^', expected: '<sub>a~b</sub> <sup>a^b</sup>', subs: ['a~b'], sups: ['a^b'], strikes: [] },
  { markdown: '~a\\\\~ ^a\\\\^', expected: '<sub>a\\</sub> <sup>a\\</sup>', subs: ['a\\'], sups: ['a\\'], strikes: [] },
  { markdown: '~open ^open', expected: '~open ^open', subs: [], sups: [], strikes: [] },
  { markdown: '~~ ^^', expected: '~~ ^^', subs: [], sups: [], strikes: [] },
  { markdown: '`~中~ ^上^ ~~删除~~`', expected: '<code>~中~ ^上^ ~~删除~~</code>', subs: [], sups: [], strikes: [] },
  { markdown: '```text\n~中~ ^上^ ~~删除~~\n```', expected: '~中~ ^上^ ~~删除~~', subs: [], sups: [], strikes: [] },
  { markdown: '~*中*~ ^<b>^ ~&amp;~', expected: '<sub>*中*</sub> <sup>&lt;b&gt;</sup> <sub>&amp;amp;</sub>', subs: ['*中*', '&amp;'], sups: ['<b>'], strikes: [] },
  { markdown: '[^missing][^other]', expected: '[^missing][^other]', subs: [], sups: [], strikes: [] },
  { markdown: '~~H~2~O~~', expected: '<s>H<sub>2</sub>O</s>', subs: ['2'], sups: [], strikes: ['H2O'] },
  { markdown: '| ~中~ ~~删除~~ \\~原文\\~ |\n| --- |\n| ^上^ `~代码~` ~two three~ |', expected: '<sub>中</sub> <s>删除</s> ~原文~', subs: ['中'], sups: ['上'], strikes: ['删除'] },
  { markdown: '| ~a\\ b~ ^a\\^b^ ~a\\\\~ |\n| --- |\n| ~~H~2~O~~ |', expected: '<sub>a b</sub> <sup>a^b</sup> <sub>a\\</sub>', subs: ['a b', 'a\\', '2'], sups: ['a^b'], strikes: ['H2O'] }
];
